services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "${APP_PORT}:3000"
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    networks:
      - nest-elk

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    env_file:
      - .env
    ports:
      - "${ELASTICSEARCH_PORT}:9200"
    networks:
      - nest-elk

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.0
    env_file:
      - .env
    ports:
      - "${KIBANA_PORT}:5601"
    networks:
      - nest-elk

networks:
  nest-elk:
    driver: bridge
