services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "${APP_PORT}:3000"
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs


