services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "${APP_PORT}:3000"
    env_file:
      - .env
    depends_on:
      - elasticsearch
    volumes:
      - ./logs:/app/logs
    networks:
      - nest-elk

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    restart: always
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    env_file:
      - .env
    ports:
      - "${ELASTICSEARCH_PORT}:9200"
    networks:
      - nest-elk

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.0
    restart: always
    env_file:
      - .env
    depends_on:
      - logstash
      - elasticsearch
    ports:
      - "${KIBANA_PORT}:5601"
    networks:
      - nest-elk

  logstash:
    image: docker.elastic.co/logstash/logstash:8.12.0
    restart: always
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
    env_file:
      - .env
    ports:
      - "${LOGSTASH_PORT}:5001"
      - "${LOGSTASH_BEATS_PORT}:5002"
    depends_on:
      - elasticsearch
    networks:
      - nest-elk

  filebeat:
    build:
      context: filebeat/
    restart: always
    environment:
      - strict.perms=false
    user: root
    volumes:
      - ./logs:/var/log/app-logs:ro
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - filebeat-data:/usr/share/filebeat/data
    depends_on:
      - logstash
      - backend
    networks:
      - nest-elk

networks:
  nest-elk:
    driver: bridge

volumes:
  filebeat-data: